"""Initial migration.

Revision ID: 60ae3b645b51
Revises: 
Create Date: 2024-10-13 16:18:59.412516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ae3b645b51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Use rename_table to rename the department table to departments
    op.rename_table('department', 'departments')
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
